[Content]
# The directory where the markdown content files are stored.
ContentDir = "content"
# Set to true if wikilinks in markdown should be enabled.
Wikilinks = true

[Web]
# The port the web server should listen on.
Port = 8080
# The directory where the static assets are stored.
AssetsDir = "assets"
# The name of the template to use for all pages. This should correspond to the 
# name of the file of the template, without any file extension.
PageTemplate = "page"
# The directory where the web templates are stored. Templates should use the 
# .tmpl extension.
TemplateDir = "templates/web"
# The directory where the generated web pages should be stored.
OutputDir = "_web"

[Gemini]
# The hostname of the Gemini server.
Hostname = "localhost"
# The port the Gemini server should listen on.
Port = 1965
# The directory where certificates should be stored.
CertStore = "/tmp"
# The name of the template to use for all pages. This should correspond to the 
# name of the file of the template, without any file extension.
PageTemplate = "page"
TemplateDir = "templates/gemini"
OutputDir = "_gemini"

[[Assets]]
SourceDir = "assets"
DestDir = "_web/assets"
